services:

  mongo:
    image: mongo
    container_name: artify-mongo
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: artify-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/artify
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: artify-frontend
    ports:
      - "5000:80"
    depends_on:
      - backend