import { api } from "./api";

export const artifyApi = {
  login: (payload) => api.post("/api/auth/login", payload),
  register: (payload) => api.post("/api/auth/register", payload),
  getProfile: () => api.get("/api/users/profile"),
  updateProfile: (payload) => api.put("/api/users/update", payload),
  getArtworks: (params = {}) => api.get("/api/artworks", { params }),
  getArtwork: (id) => api.get(`/api/artworks/${id}`),
  createArtwork: (payload) => api.post("/api/artworks", payload),
  updateArtwork: (id, payload) => api.put(`/api/artworks/${id}`, payload),
  deleteArtwork: (id) => api.delete(`/api/artworks/${id}`),
  getCategories: () => api.get("/api/categories"),
  createCategory: (payload) => api.post("/api/categories", payload),
  updateCategory: (id, payload) => api.put(`/api/categories/${id}`, payload),
  deleteCategory: (id) => api.delete(`/api/categories/${id}`),
  createOrder: (payload) => api.post("/api/orders", payload),
  getPaymentConfig: () => api.get("/api/orders/payment-config"),
  createCheckout: (payload) => api.post("/api/orders/checkout", payload),
  verifyPayment: (payload) => api.post("/api/orders/verify-payment", payload),
  getOrders: () => api.get("/api/orders"),
  getUserOrders: () => api.get("/api/orders/user"),
  updateOrder: (id, payload) => api.put(`/api/orders/${id}`, payload),
  createReview: (payload) => api.post("/api/reviews", payload),
  getReviews: (artworkId) => api.get(`/api/reviews/${artworkId}`),
  getAdminStats: () => api.get("/api/admin/stats"),
  getAdminUsers: () => api.get("/api/admin/users"),
  getAdminArtists: () => api.get("/api/admin/artists"),
  updateAdminUser: (id, payload) => api.put(`/api/admin/users/${id}`, payload),
  deleteAdminUser: (id) => api.delete(`/api/admin/users/${id}`),
  getAdminArtworks: () => api.get("/api/admin/artworks"),
  deleteAdminArtwork: (id) => api.delete(`/api/admin/artworks/${id}`),
  getAdminOrders: () => api.get("/api/admin/orders"),
  updateAdminOrder: (id, payload) => api.put(`/api/admin/orders/${id}`, payload),
  getAdminCategories: () => api.get("/api/admin/categories"),
};
